import { SearchResultResponse } from "../models";

export const mock: SearchResultResponse = {
  errors: [],
  hasErrors: false,
  success: true,
  data: {
    total: 7128,
    results: [
      {
        id: 'gfdgfbdbdb',
        image: '/item-images/item-img-1.png',
        title: 'Product 1',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'mjhmngfnfbdf',
        image: '/item-images/item-img-1.png',
        title: 'Product 2',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'nfdbvdsvgfm',
        image: '/item-images/item-img-1.png',
        title: 'Product 3',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'mhgfbdsvsvbgfmj',
        image: '/item-images/item-img-1.png',
        title: 'Product 4',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'fsvfdbbgffnbhgj',
        image: '/item-images/item-img-1.png',
        title: 'Product 5',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'ngfdfvdvfdbfgbg',
        image: '/item-images/item-img-1.png',
        title: 'Product 6',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
      {
        id: 'ngfngfnhjklmjmjm',
        image: '/item-images/item-img-1.png',
        title: 'Product 7',
        price: 1234,
        userName: 'User name',
        likes: '12',
        avatar: '/icons/userpage/user.png',
      },
    ],
    facets: [],
  },
};
